api:
  id: api_id
  on_client_connected:
    - lambda: id(init_in_progress) = false;
    - script.execute: control_leds
  on_client_disconnected:
    - script.execute: control_leds
  encryption:   # Uses key set by Home Assistant


button:
  # Restarts Sat1 Device
  - platform: restart
    name: "Restart Sat1"
    entity_category: diagnostic

  # Restores the Sat1 ESP back to factory settings
  - platform: factory_reset
    id: factory_reset_button
    name: "Factory Reset ESP32 FW"
    entity_category: diagnostic
    internal: true

  # Starts the voice assistant (start listening)
  - platform: template
    id: start_voice_assistant_button
    name: "Start Voice Assistant"
    icon: "mdi:microphone"
    entity_category: config
    on_press:
      - if:
          condition:
            lambda: return !id(init_in_progress);
          then:
            - if:
                condition:
                  switch.is_on: timer_ringing
                then:
                  - switch.turn_off: timer_ringing
                else:
                  - if:
                      condition:
                        lambda: return id(external_media_player)->state == media_player::MediaPlayerState::MEDIA_PLAYER_STATE_ANNOUNCING;
                      then:
                        - lambda: |
                            id(external_media_player)
                              ->make_call()
                              .set_command(media_player::MediaPlayerCommand::MEDIA_PLAYER_COMMAND_STOP)
                              .set_announcement(true)
                              .perform();
                      else:
                        - if:
                            condition:
                              voice_assistant.is_running:
                            then:
                              - voice_assistant.stop:
                            else:
                              - if:
                                  condition:
                                    and:
                                      - switch.is_off: master_mute_switch
                                      - not:
                                          voice_assistant.is_running
                                  then:
                                    - if:
                                        condition:
                                          switch.is_on: wake_sound
                                        then:
                                          - script.execute:
                                              id: play_sound
                                              priority: true
                                              sound_file: !lambda return id(wake_word_triggered_sound);
                                          - delay: 300ms
                                    - voice_assistant.start:

  # Stops the voice assistant
  - platform: template
    id: stop_voice_assistant_button
    name: "Stop Voice Assistant"
    icon: "mdi:microphone-off"
    entity_category: config
    on_press:
      - if:
          condition:
            voice_assistant.is_running:
          then:
            - voice_assistant.stop:


switch:
    # Wake Word Sound Switch.
  - platform: template
    id: wake_sound
    name: Wake sound
    icon: "mdi:bullhorn"
    entity_category: config
    optimistic: true
    restore_mode: RESTORE_DEFAULT_ON

    # This is the master mute switch. It is exposed to Home Assistant. The user can only turn it on and off if the hardware switch is off. (The hardware switch overrides the software one)
  - platform: template
    id: master_mute_switch
    restore_mode: RESTORE_DEFAULT_OFF
    icon: "mdi:microphone-off"
    name: Mute Microphones
    entity_category: config
    turn_on_action:
      - if:
          condition:
            binary_sensor.is_off: btn_left
          then:
            - switch.template.publish:
                id: master_mute_switch
                state: ON
    turn_off_action:
      - if:
          condition:
            binary_sensor.is_off: btn_left
          then:
            - switch.template.publish:
                id: master_mute_switch
                state: OFF
          else:
            - lambda: id(warning) = true;
            - script.execute: control_leds
    on_turn_on:
      - script.execute: control_leds
    on_turn_off:
      - script.execute: control_leds

text_sensor:
  - platform: template
    id: pd_state_text
    name: "USB-C Power Draw"
    icon: "mdi:usb-c-port"
    entity_category: "diagnostic"
    update_interval: never
    lambda: |-
      if( id(pd_fusb302b).state == power_delivery::PD_STATE_DISCONNECTED){
        return std::string("Detached");
      } else {
        return id(pd_fusb302b).contract;
      }

  - platform: template
    id: xmos_firmware_version_text
    name: "XMOS Firmware"
    icon: "mdi:memory"
    entity_category: "diagnostic"
    update_interval: never
    lambda: return id(satellite1_id).status_string();
      
